name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simple log
        run: echo "hello from action"
      - name: Say Goodbye
        run: echo "Good Bye"
